### ISSUE TITLE
vite import Unocss & run dev SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by gggso** [antfu/unocss#285]
vite: 2.7.2
unocss: 0.16.4
node: v12.22.7
![image](https://user-images.githubusercontent.com/6212790/146884472-908a630f-271a-48bf-b3f7-87047dada0b1.png)
failed to load config from /Users/gggso/web/unocss-demo/vite.config.ts
error when starting dev server:
/Users/gggso/web/unocss-demo/node_modules/@unocss/vite/dist/index.cjs:217
        return command === "build" && !options.build?.ssr;
                                                     ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/gggso/web/unocss-demo/node_modules/unocss/dist/vite.cjs:5:20)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

**Comment by gggso** [comment]
Upgrade node to 16 and it will run
